rajhack/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^',include('sfg.urls')),
    url(r'^sfg/',include('sfg.urls')),
    url(r'^admin/', admin.site.urls),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

sfg/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views
from . import feeds

urlpatterns = [
    url(r'^$',views.log, name='log'),
    url(r'^authentication/$',views.login_next, name='login_next'),
    url(r'^log_end/$',views.log_end,name='logout'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^home/$',views.apiAddBlock,name='home'),
    url(r'^dashboard/$',views.dashboard,name='dashboard'),
    url(r'^add_block/$',views.add_block,name='add_block'),
    url(r'^view_chain/$',views.view_chain,name='view_chain'),
    ]

feeds.prediction_model()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sfg/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
import hashlib as hasher


class Patient(models.Model):
    patient_id = models.AutoField(null=False,primary_key=True)
    username = models.CharField(max_length=500)
    name = models.CharField(max_length=500)

    def __unicode__(self):
        return unicode(self.name)


class Block(models.Model):
    user = models.ForeignKey(User)
    index = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)
    title  = models.CharField(max_length=250)
    image = models.CharField(max_length=5000)
    text = models.CharField(max_length=50000)
    previous_hash = models.CharField(max_length=256)
    hash = models.CharField(max_length=256)

    def __unicode__(self):
        return unicode(self.title)


class Patient(models.Model):
    patient_id = models.AutoField(null=False,primary_key=True)
    username = models.CharField(max_length=500)
    name = models.CharField(max_length=500)

    def __unicode__(self):
        return unicode(self.name)

class PatientAndBlock(models.Model):
    PATIENT_BLOCK = models.ForeignKey(
        Block,
        on_delete=models.CASCADE,
		null=True,
		blank=True,
    )
    PATIENT = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
		null=True,
		blank=True,
    )
    def __unicode__(self):
        return unicode(self.PATIENT)

sfg/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'signupinput firstname','placeholder':'First Name*'}))
    last_name = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'signupinput lastname','placeholder':'Last Name'}))
    email = forms.EmailField(max_length=254, widget=forms.EmailInput(attrs={'class': 'signupinput email','placeholder':'Email ID*'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'signupinput password1','placeholder':'Password*'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'signupinput password2','placeholder':'Confirm Password*'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        
        widgets = {
        'username': forms.TextInput(attrs={'class': 'signupinput username','placeholder':'Username*'}),      
        }

sfg/templates/sfg/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<html>
<head>
	<title> {% block title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'sfg/css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'sfg/style.css' %}" />
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
	<script src="{% static 'sfg/js/jquery-3.2.0.min.js' %}"></script>
	<script src="{% static 'sfg/js/bootstrap.min.js' %}"></script>
</head>
<body> 
	{% block content %}{% endblock %}
</body>
</html>

sfg/templates/sfg/home.html
{% extends "sfg/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}	
<div class= "container">
	<div class = "row">
		<div class = "col-md-6 col-md-offset-3"> 
			<br><br><br>
			<h1 align="center">Welcome {{user}}</h1><br>
			<div >
				<div align="center"> 
					<form>
						<button formaction="{% url 'add_block' %}" class="btn btn-primary"> Add Block&nbsp;<span class="glyphicon glyphicon-plus"></span></button>&nbsp&nbsp<button formaction="{% url 'view_chain' %}" class="btn btn-primary"> View Blockchain&nbsp; </button><br><br><br>
						<button formaction="{% url 'logout' %}" class="btn btn-danger"> Logout&nbsp; <span class="glyphicon glyphicon-log-out"></span></button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>		
{% endblock %}

sfg/templates/sfg/login.html
{% load static %}
<!DOCTYPE html>
{% block content %}
<html>
<head>
	<title>Login</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="{% static 'sfg/js/jquery-3.2.0.min.js' %}"></script>
	<script src="{% static 'sfg/js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'sfg/css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'sfg/style.css' %}" />
</head>
<body id="loginpage">
	<script>
		function fpassoverlay(){
			alert("Please Contact Admin");
		}
	</script>
	<div class="jumbotron vertical-center">
		<div class = "container">
			<div class="row vertical-align">
				<div class="col-xs-10 col-xs-offset-2 col-md-5 col-md-offset-1 formdiv">
					<h1>Login</h1>
					<form action="{% url 'login_next' %}" method="post">
						{% csrf_token %}
						<div class = "loginform">
							{% if login_message %}
							<div class="text-danger">
								{{login_message}}
							</div>
							{% endif %}
							<div class="loginfield">
								<input placeholder = "Username" type=text name=name class="logininput">
							</div>
							<div class="loginfield">
								<input type=password name=pwd placeholder="Password" class="logininput">
							</div>
						</div>
						<button class = "loginbtn btn btn-success" type="submit">Login</button>
					</form>
					<form>
						<button class = "loginbtn btn btn-register" formaction = "{% url 'signup' %}">Register</button>
					</form>
					<p><a class="fpbtn" data-toggle="modal" data-target="#forgotpass">Forgot Password?</a></p>
				</div>
			</div>
		</div>
	</div>
</body>
{% endblock %}

sfg/templates/sfg/new_block.html
{% extends "sfg/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class= "container">
	<div class = "row">
		<div class = "col-md-6 col-md-offset-3">
			<div class = "taskdetails whitecard" >
				<h3 align="center">
					<span class="pull-left"><form>
						<button class="btn btn-default" id="backbutton" formaction = "{% url 'dashboard' %}" type="submit">
							<i class=" glyphicon glyphicon-circle-arrow-left"></i>
						</button>
					</form></span>New Block</h3>
					<form action="{% url 'add_block' %}" enctype="multipart/form-data" method="post">
						{% csrf_token %}
						<table class = "addform" align="center">
							<tr>
								<th>Caption </th>
								<td><input type="text" name="caption"></td>
							</tr>
							<tr>
								<th>Report: </th>
								<td><input type="file" name="myfile"></td>
							</tr>
							<tr>
								<th> Choose Patient: </th>
								<td>
									<select name="patient">
										{% for patient in patients %}
    										<option value="{{ patient.patient_id }}">{{ patient }}</option>
										{% endfor %}
									</select>
								</td>
							</tr>
							<td><button class= "btn btn-sm btn-success" type="submit" value="Submit" >Upload</button></td>
						</table>
					</form>
					{% if uploaded_file_url %}
					<p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
					{% endif %}
					{% if file_text %}
					<p>FILE TEXT: {{ file_text }}</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	{% endblock %}

sfg/templates/sfg/signup.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'sfg/css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'sfg/style.css' %}" />
	<script src="{% static 'sfg/js/jquery-3.2.0.min.js' %}"></script>
	<script src="{% static 'sfg/js/bootstrap.min.js' %}"></script>

</head>
<body id="signuppage">
	<div class="jumbotron vertical-center">
		<div class = "container">
			<div class="row vertical-align">
				<div class="col-xs-10 col-xs-offset-2 col-md-5 col-md-offset-1 formdiv">
					<h1>Sign Up</h1>
					<form method="post">
						{% csrf_token %}
						{% for field in form %}
						<div class="fieldWrapper">
							{{ field.errors }}
							{{ field }}
						</div>
						{% endfor %}
						<button class = "loginbtn btn btn-success" type="submit">Sign Up</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
{% endblock %}

sfg/templates/sfg/view_chain.html
{% extends "sfg/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class= "container">
	<div class="row">
		<h2 align="center">
			<span class="pull-left">
				<form>
					<button class="btn btn-default" id="backbutton" formaction = "{% url 'dashboard' %}" type="submit">
						<i class=" glyphicon glyphicon-circle-arrow-left"></i>Back
					</button>
				</form>
			</span>Your BlockChain
		</h2>

		{% if user.block_set.all %}
		{% for block in user.block_set.all %}
		<div class="col-md-3">
			<table class = "taskpool"  style="display:inline;">
				<tr>
					<th> block </th>
					<th> A </th>
				</tr>
				<tr>
					<td> Title</td>
					<td>{{block.title}} </td>
				</tr>
				<tr>
					<td> Report</td>
					<td  ">{{block.text}} </td>
				</tr>
				<tr>
					<td> Image</td>
					<td><a href="{{block.image}}">view</a> </td>
				</tr>
				<tr>
					<td> Timestamp</td>
					<td>{{block.timestamp}} </td>
				</tr>
			</table>
		</div>
		{% endfor %}
		{% endif %}
		<div style="margin-top: 10px; margin-bottom: 15px;"></div>
		<table class = "taskpool">
			<tr>
				<th> <th><th> Summary<th><th></th><th></th> </th></th></th></th>
			</tr>
			<tr>
				<td><em> Your</em> </td>
				<td><em> Predicted</em></td>
				<td> <em>score:</em></td>
				<td><b> {{pred_level}}</b></td>
			</tr>
			<tr>
				<td> 0: Negative</td>
				<td> 1: Mild</td>
				<td> 2: Moderate</td>
				<td> 3: Strong</td>
				<td> 4: Severe</td>
			</tr>
		</table>
	</div>
</div>
{% endblock %}